version: '3.8'
services:
    oai-gnb:
        #temporary image
        image: phinetech/oai-gnb:eth-pdu-latest
        privileged: true
        container_name: oai-gnb
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim --log_config.global_log_options level,nocolor,time
            ASAN_OPTIONS: detect_leaks=0
        volumes:
            - ./ran-conf/gnb.sa.band78.106prb.rfsim.yaml:/opt/oai-gnb/etc/gnb.yaml
        networks:
            public_net:
                ipv4_address: 192.168.70.153
            n3_net:
                ipv4_address: 192.168.71.153
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue1:
        #temporary image
        image: phinetech/oai-ue:eth-pdu-latest
        privileged: true
        container_name: oai-nr-ue1
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim -r 106 --numerology 1 -C 3619200000 --rfsimulator.serveraddr 192.168.70.153 --log_config.global_log_options level,nocolor,time
        depends_on:
            - oai-gnb
        volumes:
            - ./ran-conf/nrue.uicc.1.yaml:/opt/oai-nr-ue/etc/nr-ue.yaml
        networks:
            public_net:
                ipv4_address: 192.168.70.154
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue2:
        #temporary image
        image: phinetech/oai-ue:eth-pdu-latest
        privileged: true
        container_name: oai-nr-ue2
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim -r 106 --numerology 1 -C 3619200000 --rfsimulator.serveraddr 192.168.70.153 --log_config.global_log_options level,nocolor,time
        depends_on:
            - oai-gnb
        volumes:
            - ./ran-conf/nrue.uicc.2.yaml:/opt/oai-nr-ue/etc/nr-ue.yaml
        networks:
            public_net:
                ipv4_address: 192.168.70.155
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    # For ETH PDU session testing
    oai-nr-ue3:
        image: phinetech/oai-ue:eth-pdu-latest
        privileged: true
        container_name: oai-nr-ue3
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim -r 106 --numerology 1 -C 3619200000 --rfsimulator.serveraddr 192.168.70.153 --log_config.global_log_options level,nocolor,time
        depends_on:
            - oai-gnb
        volumes:
            - ./ran-conf/nrue.uicc.3.yaml:/opt/oai-nr-ue/etc/nr-ue.yaml
        networks:
            public_net:
                ipv4_address: 192.168.70.156
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        external:
            name: demo-oai-public-net
    n3_net:
        external:
            name: demo-oai-n3-net

