uicc0:
  imsi: 208950000000038
  key: 0C0A34601D4F07677303652C0462535B
  opc: 63bfa50ee6523365ff14c1f45f88737d
  dnn: ethernet
  nssai_sst: 5

thread-pool: "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1"

#/* configuration for channel modelisation */
#/* To be included in main config file when */
#/* channel modelisation is used (rfsimulator with chanmod options enabled) */
channelmod:
  max_chan: 10
  modellist: modellist_rfsimu_1
  modellist_rfsimu_1:
    - model_name: rfsimu_channel_enB0
      type: AWGN
      ploss_dB: 20
      noise_power_dB: -4
      forgetfact: 0
      offset: 0
      ds_tdl: 0
    - model_name: rfsimu_channel_ue0
      type: AWGN
      ploss_dB: 20
      nose_power_dB: -2
      forgetfact: 0
      offset: 0
      ds_tdl: 0
